
#DEFINE LA IMAGEN BASE
FROM gradle:7.6-jdk11-alpine

#COPIA EL ARCHIVO JAR DE LA APLICACION EN EL CONTENEDOR
COPY . .

#BUILD
RUN gradle build

#EXPONE EL PUERTO 8080 PARA ACCEDER A LA APLICACION
EXPOSE 8080

#DEFINE EL COMANDO PARA EJECUTAR LA APLICACION AL INICIAR EL CONTENEDOR
ENTRYPOINT ["java", "-jar", "build/libs/homeBanking-0.0.1-SNAPSHOT.jar"]